services:
    picuss:
        build: .
        user: root
        container_name: picuss-server
        restart: no
        volumes:
            - ./picuss-data/database.sqlite:/app/database/database.sqlite
            - ./picuss-data/data:/app/storage/app
        # environment:
        env_file:
            - ./docker/env_file
        ports:
            - 3000:80
    yolo:
        build: ./Yolo
        container_name: yolo-image-recognison
        volumes:
            - ./picuss-data:/data
            - ./picuss-data/models:/app/models
        depends_on:
            - picuss
